# Generated by Django 2.1.5 on 2019-01-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0003_movieinfo_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=250)),
                ('job', models.CharField(blank=True, max_length=250)),
                ('workplace', models.CharField(blank=True, max_length=250)),
                ('description_of_user', models.CharField(blank=True, max_length=250)),
                ('attempt_to_login', models.IntegerField(default=0)),
                ('activated', models.IntegerField(default=0)),
                ('profile_picture', models.FileField(blank=True, upload_to='profile_pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
